KiOui/TOSTI

website/tosti/templates/tosti/base.html

Added a new header menu (and reshuffled the items).
Closes #8

New header menu

---

website/orders/templates/orders/start_shift.html
website/orders/templatetags/start_shift.py

Altered currently_active_shift_for_venue to support joining already ended shifts.
Closes #7

Alteration of currently_active_shift_for_venue

---

README.md
pyproject.toml

Changed the poetry description and author. Also changed a link in the README.

Added poetry description and changed author

---

website/orders/templates/orders/order_header.html

Fix assignees not displaying correctly
Closes #53

Fix for assignees not displaying correctly

---

website/users/forms.py

The remember username toggle was required, this is now fixed.

Fix remember username required

---

website/orders/forms.py

Changes the default starting time of the start shift form to the time it is currently, rounds down to the minute.
Closes #46

Changed the starting time to the time it is now

---

website/orders/models.py
website/orders/static/orders/js/asynch-order-overview.js
website/orders/templates/orders/item_overview.html
website/orders/templates/orders/shift_admin.html
website/orders/templatetags/order_now.py
website/orders/urls.py
website/orders/views.py

Added a button for displaying an overview for ordered products in a shift.
We might need to rethink the way the shift button is displayed now, maybe changing an icon in the bottom menu to the shift overview button?

Added a shift overview button

---

website/tosti/context_processors.py
website/tosti/settings/base.py
website/tosti/settings/production.py
website/tosti/templates/tosti/analytics.html
website/tosti/templates/tosti/base.html

Added google analytics support.
Closes #74

Added google analytics support

---

website/orders/converters.py
website/orders/static/orders/js/asynch-alter-orders.js
website/orders/templates/orders/order_items.html
website/orders/urls.py
website/orders/views.py
website/tosti/urls.py

Changed a couple of URL's to make them more fitting:
All `orders/` URLs are now changed to `shifts/` URLs.
URLs for controlling a shift are now renamed with an extra `control` path.
Closes #21

Changed urls

---

website/tosti/static/tosti/css/viewheight.css
website/tosti/templates/tosti/403.html
website/tosti/templates/tosti/404.html
website/tosti/templates/tosti/500.html
website/tosti/templates/tosti/base.html
website/tosti/urls.py
website/tosti/views.py

Added three custom error pages for 403, 404 and 50x errors.

Added custom error pages

---

website/marietje/templates/marietje/queue.html
website/marietje/templatetags/marietje.py
website/orders/templates/orders/shift_orders.html
website/users/static/users/css/centered-container.css

Some more styling fixes and a reverse on the queue.
Closes #99

Some styling fixes

---

website/marietje/services.py

Fixed a small error where an exception could be thrown by Spotify but the database was still updated with a queue item.

Fixed a small line order error

---

website/orders/views.py
website/tosti/views.py

Redirect 403's to login if not logged in

---

Dockerfile
poetry.lock
website/orders/models.py

Added a cronjob to perform data minimization
Updated poetry dependencies
Closes #94

Added cronjob and updated dependencies

---

website/orders/models.py
website/orders/static/orders/js/asynch-order-orders.js
website/users/views.py

Fixed a bug where users could order products beyond shift restrictions. Also fixes a bug where the login page could be visited by logged in users.
Closes #126

Shift restrictions bug fix

---

poetry.lock
website/tosti/settings/__init__.py

Updated all poetry dependencies.

Dependency updates

---

.github/workflows/docker.yaml

The docker build is broken. This pull request fixes that.

Fix of the docker build

---

website/thaliedje/static/thaliedje/css/search.css
website/thaliedje/templates/thaliedje/search.html

Fix the background color of the search list on the Thaliedje screens.

Fix search bar background color

---

website/tosti/static/tosti/css/base.css
website/tosti/static/tosti/css/variables.css

This fixes an issue where the greyed out button does not have the correct background color.

Fix grayed out button color on light mode

---

poetry.lock
website/tosti/settings/settings.py

Updated dependencies (particularly Django to 3.2).
Closes #154

Updated dependencies

---

poetry.lock
website/thaliedje/admin.py
website/thaliedje/admin_views.py
website/thaliedje/templates/admin/thaliedje/player/submit_line.html
website/thaliedje/templates/thaliedje/admin/authorize.html
website/thaliedje/templates/thaliedje/admin/authorize_succeeded.html
website/tosti/settings/settings.py

This pull requests includes the following:
- Updated dependencies
- Added a "Reauthorize" button to the Player admin to manually reauthorize Player objects
- Added some data to the Player admin screens so that more of the Django admin is shown
Closes #156 as this was due to invalid cache tokens

Reauthorize button and dependency update

---

website/thaliedje/api/v1/views.py
website/thaliedje/models.py
website/thaliedje/templates/thaliedje/player.html

Added javascript error messages to the player.
Closes #152

Added error messages to player

---

.github/workflows/docker.yaml

Added `buildx` to the CI for creating ARM docker images.
Closes #146

Buildx for creating ARM images

---

website/venues/templates/venues/calendar.html

Add padding underneath calendar

Fix padding on calendar view

---

website/orders/views.py
website/thaliedje/views.py

Fix an issue where a non authenticated user was not able to acces the Thaliedje now playing view.

Fix exception on thaliedje view

---

website/orders/views.py

Refactored the `CreateShiftView` to a `CreateView`.
Closes #205

Refactored view to CreateView

---

poetry.lock
pyproject.toml
website/venues/urls.py
website/venues/views.py

Added calendar exports for venue reservations.

Added calendar export

---

website/tosti/static/tosti/css/base.css
website/tosti/templates/tosti/base.html

Added an off canvas menu for the header bar.

Added offcanvas menu

---

website/orders/api/v1/views.py

Fix permission denied bug for update view

Fix bug permission denied

---

website/borrel/forms.py

Added association data field to reservation when creating a borrel reservation.

Added association data to reservation object

---

website/borrel/admin.py
website/orders/admin.py
website/thaliedje/admin.py

Autocomplete fields for two admins

---

website/tosti/templates/tosti/privacy.html

Improve privacy policy

---

website/borrel/views.py
website/orders/api/v1/views.py
website/orders/views.py
website/tosti/api/views.py
website/tosti/utils.py
website/venues/views.py

Add django admin logs to api and views

---

website/thaliedje/api/v1/serializers.py
website/thaliedje/api/v1/views.py
website/thaliedje/templates/thaliedje/queue.html

Improve thaliedje requested songs

---

website/borrel/templates/borrel/borrel_reservation_warning.html
website/borrel/templatetags/borrel_reservations.py
website/tosti/templates/tosti/index.html

Warnings to submit borrel reservation on index.html

---

website/thaliedje/services.py
website/thaliedje/templates/thaliedje/now_playing.html
website/thaliedje/templates/thaliedje/search.html
website/thaliedje/views.py

Changed the following:
* Added album art when searching for tracks, playlists and albums.
* Changed the interface for the search box when on desktop.
* Added a confirm popup when a user requests to start playing an album or playlist.
Closes #280 
Closes #279

Add album art and change interface of search box

---

website/thaliedje/admin.py
website/thaliedje/admin_views.py
website/thaliedje/converters.py

Fix blank slug bug

---

website/orders/models.py
website/orders/tests/test_models.py

Don't update end time when shift is not active

---

website/orders/templates/orders/order_list.html
website/orders/templates/orders/shift_admin_scanner.html

Added price formatting via `Intl`, also fixes a bug where price formatting was broken due to API changes.
Closes #322

Added Intl price formatting to order pages

---

website/tosti/static/tosti/js/base.js

Refresh timeout to 20 seconds

---

website/tantalus/admin.py
website/tantalus/templates/admin/orders/shift/submit_line.html
website/thaliedje/models.py

Added a push to tantalus button on the Shift admin screen which rerun's the push to Tantalus in case of failures.
Closes #349

Added a push to tantalus button on the admin screen of Shifts

---

README.md
pyproject.toml

The python version in the README.md and the pyproject.toml now reflects the python version of lilo

Different python versions

---

website/orders/templates/orders/order_admin_list.html
website/orders/templates/orders/order_admin_order.html

Closes #287.
This simple solution should help solve the problem of multiple Max/Tims.
Try out by just looking at the order list.

Add full name on admin order page

---

website/tosti/templates/tosti/venue_card.html

Added day of the reservation to the reservation to fix #358

---

website/borrel/forms.py
website/borrel/templates/borrel/borrel_reservation_submit.html
website/borrel/views.py
website/thaliedje/models.py
website/tosti/settings/base.py

Added a checkbox when submitting a borrel reservation to check whether people have looked at the cleaning schedule and cleaned the canteens.
Closes #336

Add Checkbox for cleaning the canteens when submitting borrel reservation

---

website/venues/api/v1/filters.py

Add is_ordervenue filter to venue api

---

website/orders/admin.py
website/orders/templates/orders/order_admin_order.html
website/orders/templates/orders/shift_admin_footer.html

Removes the order inlines from the django shift admin entirely, and instead adds buttons to edit a specific order and to create an order to the vue admin.

Fix slow shift admin

---

website/tosti/settings/base.py
website/venues/services.py

Add ability to mail multiple people for reservations

---

website/thaliedje/templates/thaliedje/player.html
website/tosti/static/tosti/js/base.js

Increases the refresh rate of several pages.
Closes #377

Increase the refresh speed

---

poetry.lock
pyproject.toml
website/thaliedje/crons.py
website/tosti/django_cron_app_config.py
website/tosti/settings/base.py

Add django cron

---

website/announcements/middleware.py
website/announcements/templates/announcements/announcements.html
website/announcements/templatetags/announcements.py
website/orders/apps.py
website/thaliedje/apps.py
website/tosti/settings/base.py

Add a message when the user is blacklisted in either Thaliedje or the orders app.
Closes #275

Add announcements when user is blacklisted

---

website/tosti/services.py
website/tosti/settings/base.py
website/tosti/static/tosti/js/statistics.js
website/tosti/templates/tosti/base.html
website/tosti/templates/tosti/statistics.html
website/tosti/urls.py
website/tosti/views.py

Add a statistics page for TOSTI.
Closes #38

Add statistics page

---

website/orders/tests/test_models.py
website/orders/tests/test_services.py
website/orders/tests/test_views.py
website/tantalus/tests/test_services.py
website/tosti/tests/test_views.py
website/venues/tests/test_forms.py
website/venues/tests/test_views.py

Fix the apparently new way black formats things.

Fix new black formatting

---

website/tosti/static/tosti/js/statistics.js

Fixes access to DOMProperties on statistics page.

Fix for non-safari browsers

---

website/tosti/services.py
website/tosti/templates/tosti/statistics.html
website/tosti/views.py

Add beer per month statistics.
Closes #440

Add more statistics to the statistics page

---

website/tosti/services.py
website/tosti/templates/tosti/statistics.html
website/tosti/views.py

Lars kan niet programmeren

---

website/orders/api/v1/views.py
website/orders/tests/test_api.py
website/tosti/api/v1/pagination.py
website/venues/api/v1/filters.py
website/venues/api/v1/serializers.py
website/venues/api/v1/urls.py
website/venues/api/v1/views.py
website/venues/templates/venues/calendar.html
website/venues/tests/test_api.py

Add reservation POST endpoint

---

website/venues/static/venues/css/calendar.css
website/venues/templates/venues/calendar.html

Closes #176 and fixes a bug where unaccepted reservations were always shown in the calendar.

Use a function to fetch fullcalendar events

---

website/orders/templates/orders/order_list.html
website/silvasoft/crons.py

disable prioritize when deprioritizing orders

---

deploy.sh

Change the deploy script to use local key.

Change deploy script

---

website/tosti/templates/tosti/venue_card.html
website/users/signals.py

Fixed:
- Background color of the card footer where an event was placed on light mode
- When a user is changed, `is_staff` is now adjusted accordingly
Closes #476

Apply multiple small bug fixes

---

website/orders/templates/orders/order_admin_list.html
website/orders/templates/orders/order_list.html
website/orders/templates/orders/shift_admin_footer.html
website/orders/templates/orders/shift_admin_scanner.html
website/orders/templates/orders/shift_admin_transaction_modal.html
website/orders/templates/orders/shift_header.html
website/thaliedje/templates/thaliedje/player.html
website/thaliedje/templates/thaliedje/queue.html
website/thaliedje/templates/thaliedje/requests.html
website/thaliedje/templates/thaliedje/search.html
website/tosti/templates/tosti/base.html

Remove importmaps everywhere

---

website/orders/templates/orders/order_admin_order.html
website/orders/templates/orders/order_list.html
website/orders/templates/orders/shift_admin_footer.html
website/orders/templates/orders/shift_header.html

Fix colorblindness for red/green

---

website/thaliedje/models.py
website/thaliedje/templates/thaliedje/player.html

This PR adds time indication for the Marietje player. It also fixes a bug where the actual time in minutes and seconds was not shown anymore.

Add time indication for marietje player

---

website/fridges/services.py
website/tosti/settings/base.py

Kijk eens, dit is elegante code

Add daily opening requirement

---

website/orders/templates/orders/order_admin_list.html
website/orders/templates/orders/order_admin_order.html

closes #528
order_admin_list.html
- copied this function here, we could choose to move it to the shift header/footer files or make a function template but that felt like overdoing it
order_admin_order.html
- line 18, 19 and 20 are new, 18 is a bit ugly but was needed for keeping the col spacing uniform. Alternatives were more complex

add deprioritize function for bakers

---

website/status_screen/templates/status_screen/venue_status_screen.html
website/status_screen/views.py
website/tosti/static/tosti/js/base.js
website/tosti/static/tosti/js/base64.js

You can enable OAuth2 by setting `TOSTI_CLIENT_ID` and `TOSTI_CLIENT_SECRET` cookie values to values retrieved from the admin. Create a Client Credentials OAuth application and copy over the ID and secret.

OAuth2 support for status screen
